---
products:
  auditbeat:
    upgrade_code: 89EAA6B0-0CAC-4DA4-AA58-C6C2632AA341
    published_name: Elastic Beats Autditbeat
    published_url: https://www.elastic.co/products/beats/auditbeat
    description: Audit the activities of users and processes on your system
    mutable_dirs: [ kibana ]

  filebeat:
    upgrade_code: 830E6D05-2CDB-4F5D-AACC-80B7EED19D43
    published_name: Elastic Beats Filebeat
    published_url: https://www.elastic.co/products/beats/filebeat
    description: Filebeat sends log files to Logstash or directly to Elasticsearch
    mutable_dirs: [ kibana, module, modules.d ]

  heartbeat:
    upgrade_code: E3C93134-2403-4FCD-B816-85DD37B2C7BC
    published_name: Elastic Beats Heartbeat
    published_url: https://www.elastic.co/products/beats/heartbeat
    description: Ping remote services for availability and log results to Elasticsearch or send to Logstash
    mutable_dirs: [ kibana, monitors.d ]

  metricbeat:
    upgrade_code: 79A65434-259C-4E71-9A10-B69FA34848A3
    published_name: Elastic Beats Metricbeat
    published_url: https://www.elastic.co/products/beats/metricbeat
    description: Metricbeat is a lightweight shipper for metrics
    mutable_dirs: [ kibana, module, modules.d ]

  packetbeat:
    upgrade_code: 48C5CD3B-C42A-4D6C-9D4A-D8BAF83F05BA
    published_name: Elastic Beats Packetbeat
    published_url: https://www.elastic.co/products/beats/packetbeat
    description: Packetbeat analyzes network traffic and sends the data to Elasticsearch
    mutable_dirs: [ kibana ]

  winlogbeat:
    upgrade_code: 18DE3315-EA8A-4B00-9394-2CF1523F3968
    published_name: Elastic Beats Winlogbeat
    published_url: https://www.elastic.co/products/beats/winlogbeat
    description: Winlogbeat ships Windows event logs to Elasticsearch or Logstash
    mutable_dirs: [ kibana, module ]
